travis:
  secure:
    BINSTAR_TOKEN: f5uOOIItyWr8CLvi1L4fCkIB2Ty15MahaMht66EP2Mxjec+MRUPhMqVJKPDofxoYfsT1lukjIOmSDEEob12vxBtxArD0cCT/bQT+2aoLvIUirJ/lY0ionVzXI2YHcPotRyW4vB20eM7KFbjlj710tBQ7pcsBGXUZO4atmzSozASuQg544vGaB1Q1LmYH5XxbWrXSXD+/UIii1D/qj/9WApzd7q3BOMHCcaAq5WqV/LkanXc1rorBsanF7sV28/vabJu1GA6jrUGkjg7RUZMXXgnKu4UkFF741s/byCTNxWWx2+b0MPbgQ5G1LgvdSmgVe1AKVICvvyHyVggH9D6Jch3yQ6wkJkwHnEpcvKllVMykfqJaNefHvBiRDdED6cSF08BRmIN26uQ4yId/+PBBN24Z+Ad1Wi+xrrs2jH2qzjgQbuzrmP4YIWtfYwRU/N482cVM8ySOKFprF3hBM+Q0on7SRxVv+VAIive+xysUZosTExXXPC3A6Re4YzEE0r1pKyO5/DoeKW5Ip0+mRGpZpQaA3xkcYnewq2bf7uRRNwiZU51JdbO0mH4EhrmM42Fxql3OXn/6asV9Wg/MfdNjPpc6RSZBgU1OTsePAlDIfmMIxuf311+VZvqyj1O5/9JQmmnizqPwrtjZzauqYiCb55cRKSnbYaiavUOhu7aziYg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
