appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: alynY3VzNFsfUU2Kilg7NZ1L7cmEl6cuUQJzgpHwAB5k8Tf2FpaORUynFG87LLmXw78LwZJhL4WCgPgZR3g+vVNYqvEruzlRiIt7FgYqkivdwVrzIg2eZbXI1L96a+li9ptDTurUG9/TxflUxQO/L3PogLvV68G5XQjmclDDpIPdsTmCCQvFmepmlqhiMTk5hmN9wDzXwYsliqosZopWBII9yvyv9u/jFTrM3x77ioJNhiOARAUAkzVIfzd8+I2Cz7xdGIouafxtpzgZbZrsIvLVJcl8v0ZKYP+QljPj8BFKYW4j5+8LKS1kHBcDe/CjQuHtDgohVR4JNkF6HBWgvGWRMwQkN2aoGRpTaKJ3G5l6ETxLUF0QPLSBymO+3eSXYMW07Mc2J+bYNlE/x2rDYG0fPe0nt+4KMQW4kLpJJztm3metplPl7RPzZD4fZJrxLmrXb0g6jNjI/CU3yJ0r8J7oAhLBFXzO+ulQ5Hd7/iVwtCZgZuSsDyQbFl1VRuqh0CjGZuYunLsw5VtQXFBqnoWIl82ejLg+OzRfmBNsfOhCC6eRoGr+LLR0Bio22XUB/NuB8vHFVHPhU/QbDIEnlK6hi2pke7k9tiJtu+6QooDJWzi5Q8hNaQ5aFn9MosfLkxQGHtcRSh9hwLzJBf7xyXsQHSwhnFi/heSLMd1Q00k=
